### ISSUE TITLE
왜 Optional로 하셨는지 설명해주세요

### ISSUE THREAD

**Issue by ilyoil2** [CUTY-DMS/10_CMD_BACKEND#10]
![image](https://github.com/user-attachments/assets/915527c3-a998-437c-95f9-eb099f3b6272)

**Comment by kkm06100** [comment]
생각해보니 어차피 null로 들어와도 예외로 다 걸러지니까 NPE가 안일어나서 Optional일 필요가 없을 것 같네요. 수정하는게 맞을까요?

**Comment by ilyoil2** [comment]
유저 상세보기를 했는데 null로 들어오는 경우는 없으니까 Optional로 할 필요가 없을 것 같아요

**Comment by kkm06100** [comment]
넵
