### ISSUE TITLE
정적 팩토리 메소드의 네이밍을 of 혹은 from 로 하는 걸 지향해 주세요

### ISSUE THREAD

**Issue by zios0707** [CUTY-DMS/10_CMD_BACKEND#13]
https://github.com/CUTY-DMS/10_CMD_BACKEND/blob/3b89318a792544f83652655808991a6dc96b4478/cmd_backend/src/main/java/com/gdsc/cmd/domain/notification/dto/NotificationFindResponseDto.java#L14-L18

위와 같은 정적 팩토리 메소드 네이밍보다 of, from ... 과 같은 네이밍을 하는걸 추천해요.

자세한 건 아래를 참고해주세요

https://docs.oracle.com/javase/tutorial/datetime/overview/naming.html

**Comment by ryujaemin08** [comment]
프로젝트 마감이 급해서 잘 확인 하지 못했네요... 지금이라도 수정했습니다!
