### ISSUE TITLE
유저 엔티티에 @Cacheable @DynamicInsert 어노테이션을 사용한 이유가 무엇인가요?

### ISSUE THREAD

**Issue by ilyoil2** [CUTY-DMS/10_CMD_BACKEND#3]
![image](https://github.com/user-attachments/assets/7f11e930-e113-44c3-94cf-bad9175885e4)

해당 어노테이션을 사용한 이유가 있을까요?

**Comment by zios0707** [comment]
그 assign을 님이 하시는게 맞나요?

**Comment by kkm06100** [comment]
솔직히 말하자면 디버깅 과정에서 여러가지 코드 따라해 보다가 삭제를 못 한 것 같습니다... 죄송합니다.
