### ISSUE TITLE
DTO 를 사용해 주세요

### ISSUE THREAD

**Issue by zios0707** [CUTY-DMS/10_CMD_BACKEND#5]
https://github.com/CUTY-DMS/10_CMD_BACKEND/blob/d411eb6b3c9768df8289d2311f1748140c4b43dd/cmd_backend/src/main/java/com/gdsc/cmd/domain/auth/controller/AuthController.java#L26-L28

DTO를 사용하지 않고 그대로 이러한 객체를 바로 내보내는 것은 확장성에서나 RESTful 구조에서나 벗어난다고 생각합니다.

https://github.com/CUTY-DMS/10_CMD_BACKEND/blob/d411eb6b3c9768df8289d2311f1748140c4b43dd/cmd_backend/src/main/java/com/gdsc/cmd/domain/user/controller/UserController.java#L18-L20

위와 같은 상황에서도 List<User> 를

`
public class UsersResponse {
	private List<User> users
}
`

이렇게 래핑해 주는 걸 지양해 주세요

**Comment by zios0707** [comment]
찾아보니 해당 DTO를 이미 만들어 놓으셨더라구요.

커밋 할 때 마다 하나의 기능을 집중적으로 커밋하고 다음 기능을 커밋하는 걸 추천해 드려요.
**협업 중에** 여러 파일을 한 번에 커밋하게 되면 커밋 히스토리가 굉장히 혼잡해져 디버깅이 어려워 질 수 있고,
진전 상황이 어떤지 알기 어려워요.

**Comment by kkm06100** [comment]
넵 감사합니다
