### ISSUE TITLE
회원가입 로직 확인해주세요

### ISSUE THREAD

**Issue by ilyoil2** [CUTY-DMS/10_CMD_BACKEND#6]
![image](https://github.com/user-attachments/assets/1423c9fc-4bb7-4c38-9083-61616461a5e2)

response를 현재 String으로 해주고 있는데 왜 Servce에서는 TokenResponse를 반환하는건가요?
teacherSignup로 그러함

![image](https://github.com/user-attachments/assets/b3197dd7-13c0-4815-9a55-1eee591feef5)

**Comment by kkm06100** [comment]
수정 했습니다.
