### ISSUE TITLE
세터 어노테이션 지양해주세요

### ISSUE THREAD

**Issue by ilyoil2** [CUTY-DMS/10_CMD_BACKEND#7]
![image](https://github.com/user-attachments/assets/a3085654-058d-4985-bebf-38ceca110de1)

**Comment by ilyoil2** [comment]
DTO 말고 response, request로 좀 더 명시적이게 수정해주세요

**Comment by ryujaemin08** [comment]
수정 완료했습니다. 그런데 세터 어노테이션은 왜 쓰면 안되나요?

**Comment by ilyoil2** [comment]
구글링 ㄱㄱ

**Comment by ryujaemin08** [comment]
완료했습니다
